# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 19:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20160504_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 5, 4, 19, 55, 12, 565959, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
